name: "Test Issue"
description: File any issue related to tests
title: "test: short description"
projects: ["zama-ai/35"] # blokchain division project
type: test
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      description: |
        Please describe the issue in detail.
    validations:
      required: true
