# Run tests
name: contracts-pauser-set-wrapper-tests

on:
  pull_request:
    paths:
      - '.github/workflows/contracts-pauser-set-wrapper-tests.yml'
      - 'contracts/pauserSetWrapper/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/contracts-pauser-set-wrapper-tests.yml'
      - 'contracts/pauserSetWrapper/**'
  workflow_dispatch:

permissions: {}

concurrency:
  group: ci-contracts-pauser-set-wrapper-tests-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  tests:
    name: contracts-pauser-set-wrapper-tests/tests (bpr)
    runs-on: ubuntu-latest
    permissions:
      contents: 'read' # Required to checkout repository code
    steps:
      - name: Checkout project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: 'false'

      - name: Install dependencies
        working-directory: contracts/pauserSetWrapper
        run: npm ci

      - name: Run unit tests
        working-directory: contracts/pauserSetWrapper
        run: make test
